Find the nearest value from a given value in an array

In [1]:
import numpy as np

def find_nearest_value(arr, value):
    idx = np.abs(arr - value).argmin()
    nearest_value = arr[idx]
    return nearest_value

# eg
arr = np.array([2, 5, 8, 11, 13])
value = 9

nearest = find_nearest_value(arr, value)
print(nearest)


8


Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

In [2]:
import numpy as np

array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

iterator = np.nditer([array1, array2])

sum_result = 0

for x, y in iterator:
    sum_result += x + y

print("Sum:", sum_result)


Sum: 63


 Create an array class that has a name attribute 

In [3]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=None):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', None)

arr = NamedArray([1, 2, 3], name="My Array")
print(arr) 


[1 2 3]


Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices

In [4]:
given_vector = np.array([10, 20, 30, 40, 50])

indices_vector = np.array([0, 1, 3, 1, 4])

given_vector[indices_vector] += 1

print(given_vector)

[11 21 30 41 51]


How to accumulate elements of a vector (X) to an array (F) based on an index list (I)

In [5]:
X = np.array([1, 2, 3, 4, 5])  
I = np.array([0, 1, 0, 2, 1])  
F = np.zeros(3)  

np.add.at(F, I, X)

print(F)

[4. 7. 4.]


Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

Considering a four dimensions array, how to get sum over the last two axis at once

In [6]:
arr = np.random.randint(0, 10, size=(2, 3, 4, 5))
sum_last_two_axes = np.sum(arr, axis=(-2, -1))

print(sum_last_two_axes)

[[ 72  94  97]
 [101  80 114]]


Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

In [7]:
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])  
S = np.array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])    

subset_means = []
unique_subsets = np.unique(S)  

for subset_index in unique_subsets:
    subset = D[S == subset_index]  
    subset_mean = np.mean(subset)  
    subset_means.append(subset_mean)

print(subset_means)

[5.0, 6.0]


How to get the diagonal of a dot product? 

In [8]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
dot_product = np.dot(array1, array2)
diagonal = np.diagonal(dot_product)
import numpy as np

# Create two arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Compute the dot product
dot_product = np.dot(array1, array2)

# Get the diagonal elements
diagonal = np.diagonal(dot_product)

print(diagonal)


[19 50]


Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value

In [9]:
import numpy as np

original_vector = np.array([1, 2, 3, 4, 5])

num_zeros = 3

new_length = len(original_vector) + (len(original_vector) - 1) * num_zeros

new_vector = np.zeros(new_length)

new_vector[::num_zeros + 1] = original_vector

print(new_vector)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Compute a matrix rank 

In [10]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

print("Matrix rank:", rank)


Matrix rank: 2


 How to find the most frequent value in an array

In [11]:
arr = np.array([1, 2, 3, 2, 1, 2, 4, 5, 4, 2, 1])
values, counts = np.unique(arr, return_counts=True)
max_count_index = np.argmax(counts)
most_frequent_value = values[max_count_index]

print("Most frequent value:", most_frequent_value)

Most frequent value: 2


Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [12]:
matrix = np.random.rand(10, 10)
blocks = np.lib.stride_tricks.sliding_window_view(matrix, (3, 3))
for block in blocks:
    print(block)

[[[0.50154917 0.92667943 0.69243684]
  [0.26221101 0.59322844 0.66476421]
  [0.92626957 0.02630059 0.52137596]]

 [[0.92667943 0.69243684 0.97585348]
  [0.59322844 0.66476421 0.14547209]
  [0.02630059 0.52137596 0.26316576]]

 [[0.69243684 0.97585348 0.17451492]
  [0.66476421 0.14547209 0.50294922]
  [0.52137596 0.26316576 0.74906877]]

 [[0.97585348 0.17451492 0.29171457]
  [0.14547209 0.50294922 0.10270594]
  [0.26316576 0.74906877 0.83798629]]

 [[0.17451492 0.29171457 0.20068858]
  [0.50294922 0.10270594 0.61884465]
  [0.74906877 0.83798629 0.96636052]]

 [[0.29171457 0.20068858 0.9827041 ]
  [0.10270594 0.61884465 0.00657335]
  [0.83798629 0.96636052 0.16095849]]

 [[0.20068858 0.9827041  0.01968124]
  [0.61884465 0.00657335 0.81499612]
  [0.96636052 0.16095849 0.81363475]]

 [[0.9827041  0.01968124 0.38549219]
  [0.00657335 0.81499612 0.87474766]
  [0.16095849 0.81363475 0.84989634]]]
[[[0.26221101 0.59322844 0.66476421]
  [0.92626957 0.02630059 0.52137596]
  [0.5242096  0.956761

 Consider a 16x16 array, how to get the block-sum (block size is 4x4)

In [13]:
import numpy as np

arr = np.arange(256).reshape(16, 16)
block_shape = (4, 4)
block_arr = arr.reshape(arr.shape[0] // block_shape[0], block_shape[0],
                        arr.shape[1] // block_shape[1], block_shape[1])

block_sum = np.sum(block_arr, axis=(-2, -1))

print(block_sum)


[[ 120  376  632  888]
 [1144 1400 1656 1912]
 [2168 2424 2680 2936]
 [3192 3448 3704 3960]]


How to get the n largest values of an array

In [14]:
def get_n_largest(arr, n):
    indices = np.argpartition(arr, -n)[-n:]
    
    sorted_indices = indices[np.argsort(arr[indices])][::-1]
    
    largest_values = arr[sorted_indices]
    
    return largest_values

arr = np.array([4, 9, 2, 7, 5, 1, 6, 8, 3])
n = 3

largest_values = get_n_largest(arr, n)
print(largest_values)


[9 8 7]


How to create a record array from a regular array

In [15]:
regular_array = np.array([(1, 'John', 25),
                         (2, 'Jane', 30),
                         (3, 'Alice', 28)],
                        dtype=[('id', int), ('name', 'U10'), ('age', int)])

record_array = np.rec.array(regular_array)

print(record_array.id)   
print(record_array.name) 
print(record_array.age)  


[1 2 3]
['John' 'Jane' 'Alice']
[25 30 28]


 Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [16]:
import numpy as np

Z = np.array([1, 2, 3, 4, 5])  

Z_cubed = np.power(Z, 3)
print(Z_cubed)


[  1   8  27  64 125]


In [17]:
Z = np.array([1, 2, 3, 4, 5])  

Z_cubed = Z ** 3
print(Z_cubed)

[  1   8  27  64 125]


In [18]:
Z = np.array([1, 2, 3, 4, 5])  

Z_cubed = np.multiply(Z, np.multiply(Z, Z))
print(Z_cubed)

[  1   8  27  64 125]


Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])

Given a two dimensional array, how to extract unique rows?

In [20]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [1, 2, 3],
                [7, 8, 9],
                [4, 5, 6]])

unique_rows = np.unique(arr, axis=0)

print(unique_rows)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n

In [21]:
import numpy as np

def select_multinomial_rows(X, n):
    selected_rows = []
    for row in X:
        if np.all(np.equal(np.mod(row, 1), 0)) and np.sum(row) == n:
            selected_rows.append(row)
    return selected_rows
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [2, 4, 6]])
n = 12

selected_rows = select_multinomial_rows(X, n)
for row in selected_rows:
    print(row)


[2 4 6]
